#!/usr/bin/env python3
"""Modify a Makefile generated by STM32CubeMx

######################################
# target
######################################
"""

import re
from pathlib import Path
from typing import List, Optional, Tuple


SECTION_HEADER_RE = re.compile(r"^#{3,}\s*$")
HEADLINE_RE = re.compile(r"^#\s*(.+?)\s*$")


def detect_newline(text: str) -> str:
    return "\r\n" if "\r\n" in text else "\n"


def normalize_text(text: str, newline: str) -> str:
    if not text:
        return ""
    if text.endswith(("\r", "\n")):
        return text
    return text + newline


def find_section(lines: List[str], section_name: str, case_sensitive: bool) -> Optional[Tuple[int, int]]:
    """Return (header_line_index, headline_line_index) for a matching section."""
    target = section_name if case_sensitive else section_name.lower()

    for idx in range(len(lines) - 1):
        header = lines[idx].rstrip("\r\n")
        headline = lines[idx + 1].rstrip("\r\n")

        if not SECTION_HEADER_RE.match(header):
            continue

        match = HEADLINE_RE.match(headline)
        if not match:
            continue

        title = match.group(1).strip()
        if (title if case_sensitive else title.lower()) == target:
            return idx, idx + 1

    return None


def _is_section_header(lines: List[str], index: int) -> bool:
    if index + 1 >= len(lines):
        return False
    if not SECTION_HEADER_RE.match(lines[index].rstrip("\r\n")):
        return False

    headline = lines[index + 1].rstrip("\r\n")
    if not HEADLINE_RE.match(headline):
        return False

    if index + 2 < len(lines) and SECTION_HEADER_RE.match(lines[index + 2].rstrip("\r\n")):
        return True

    return True


def _find_section_bounds(lines: List[str], section_name: str, case_sensitive: bool) -> Optional[Tuple[int, int, int]]:
    target = section_name if case_sensitive else section_name.lower()

    for idx in range(len(lines) - 1):
        if not _is_section_header(lines, idx):
            continue

        headline = lines[idx + 1].rstrip("\r\n")
        title = headline[1:].strip() if headline.startswith("#") else headline.strip()
        if (title if case_sensitive else title.lower()) != target:
            continue

        header_end = idx + 1
        if idx + 2 < len(lines) and SECTION_HEADER_RE.match(lines[idx + 2].rstrip("\r\n")):
            header_end = idx + 2

        section_end = len(lines)
        for section_idx in range(header_end + 1, len(lines)):
            if _is_section_header(lines, section_idx):
                section_end = section_idx
                break

        return idx, header_end, section_end

    return None


def insert_at_begin_section(path: Path, section_name: str, text: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Error: file not found: {path}")

    original_text = path.read_text(encoding="utf-8")
    newline = detect_newline(original_text)
    lines = original_text.splitlines(keepends=True)

    section = _find_section_bounds(lines, section_name, case_sensitive=False)
    if section is None:
        raise ValueError(f"Error: section '{section_name}' was not found")

    _, header_end, _ = section
    insertion = normalize_text(text, newline)
    lines.insert(header_end + 1, insertion)

    updated_text = "".join(lines)
    path.write_text(updated_text, encoding="utf-8")


def insert_at_end_section(path: Path, section_name: str, text: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Error: file not found: {path}")

    original_text = path.read_text(encoding="utf-8")
    newline = detect_newline(original_text)
    lines = original_text.splitlines(keepends=True)

    section = _find_section_bounds(lines, section_name, case_sensitive=False)
    if section is None:
        raise ValueError(f"Error: section '{section_name}' was not found")

    _, _, section_end = section
    insertion = normalize_text(text, newline)
    lines.insert(section_end, insertion)

    updated_text = "".join(lines)
    path.write_text(updated_text, encoding="utf-8")


def sign_makefile(path: Path, signature: str) -> int:
    if not path.exists():
        raise FileNotFoundError(f"Error: file not found: {path}")

    original_text = path.read_text(encoding="utf-8")
    if signature in original_text:
        return 1

    newline = detect_newline(original_text)
    signed_text = f"{signature}{newline}{original_text}"
    path.write_text(signed_text, encoding="utf-8")
    return 0


def remove_text(path: Path, target: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Error: file not found: {path}")

    text = path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    target_lines = target.splitlines()

    if not target_lines:
        return

    normalized_target_lines = ["".join(line.split()) for line in target_lines]

    for start_index in range(len(lines) - len(target_lines) + 1):
        matched = True
        for offset, target_line in enumerate(normalized_target_lines):
            line_text = "".join(lines[start_index + offset].split())
            if line_text != target_line:
                matched = False
                break

        if matched:
            del lines[start_index:start_index + len(target_lines)]
            path.write_text("".join(lines), encoding="utf-8")
            return

    raise ValueError(f"Error: target text not found")


if __name__ == "__main__":
    result = sign_makefile(Path("Makefile"), "# makefile modified")
    if result == 1:
        print("Makefile already signed")
    else:
        remove_text(Path("Makefile"), "$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile \n $(CC) $(OBJECTS) $(LDFLAGS) -o $@ \n $(SZ) $@")
        remove_text(Path("Makefile"), "BUILD_DIR = build\n")

        insert_at_begin_section(Path("Makefile"), "target", "-include make_args.mk\n")
        insert_at_end_section(Path("Makefile"), "CFLAGS", "-include make_mros.mk\n")
        insert_at_end_section(Path("Makefile"), "build the application", "-include make_cpp.mk\n")

	
	