topics:
  sensorMeasurements: /sensor/measurements
  sensorCalibration: /sensor/calibration
  motionControl: /motion_control
  vehicleStateEkf: /vehicle_state_ekf
  vehicleStateCsm: /vehicle_state_csm
  vehicleState: /vehicle_state_ekf
  vehicleStateAct: /vehicle_state_actual
  histVehicleStateEkf: /hist_vehicle_state_ekf
  histVehicleStateCsm: /hist_vehicle_state_csm
  histVehicleStateAct: /hist_vehicle_state_actual
  nodeState: /node_state
  laserScan: /scan

frames:
  map: map
  odom: odom
  vehBase: base_link
  vehBaseEkf: base_link_ekf
  vehBaseLidar: base_link_lidar
  lidar: lidar

sensors:
  imu:
    pos_chassis:
      x: 0
      y: 0
      z: 0
    stddev:
      accel: 0.02
      yaw_rate: 0.01
  lidar:
    pos_chassis:
      x: 0
      y: 0
      z: 0.3
    stddev: 0.005
  potentiometer:
    stddev: 0.0001
  wheelencoder:
    stddev: 0.0001

vehicle:
  wheelbase: 0.14
  wheeltrack: 0.1
  chassis:
    main:
      length: 0.13
      width: 0.08
      height: 0.02
      mass: 1.15
    front:
      length: 0.04
      width: 0.03
      height: 0.02
  wheels:
    radius: 0.015
    width: 0.015
    mass: 0.1




